### ISSUE TITLE
Ability to pass no-metadata option?

### ISSUE THREAD

**Issue by DreamOfGit** [derrian-distro/LoRA_Easy_Training_Scripts#102]
I couldn't see anywhere to disable metadata or feed custom arguments.

Am I blind?

**Comment by derrian-distro** [comment]
ah yeah, I don't plan on adding it.

**Comment by DreamOfGit** [comment]
You won't add a --no_metadata flag or you won't add the ability to pass custom arguments to Kohya?

**Comment by derrian-distro** [comment]
no, I am a firm believer that metadata shouldn't be removed

**Comment by DreamOfGit** [comment]
I understand your point.. my real issue is this:

If there was an extension / tool that I could use so that: 
- the model name was useful to the public (not using my local model name but instead being labelled as part of the NAI / SD family)
- the buckets were generic (not my bucket names but just generic placeholder bucket names)
- the tags were preserved (or keep bucket names if there's no tags)

I wouldn't need this.. but as things are right now, the simplest option is to just hard code `f"--no_metadata",` on the train_network call. ¯\_(ツ)_/¯ 

I can't even modify the metadata in notepad because there's some kind of byte count checksum. 

Thanks for the response.

**Comment by derrian-distro** [comment]
Additional networks allows you the ability to add things like a description and model name to your model, granted it's only really visible on the extension, but I'm sure it can be supported in other ways, if people actually cared.
I don't know what you are saying when you refer to buckets, they aren't named as they are solely just the information about the sizes of images used.
if you mean the tag occurrence stuff, which has the folder names in them, that can probably be changed in the future, If I want to spend the time figuring out how kohya handles metadata. But I personally don't see any problems with the metadata as it is currently, as the folder names are only the actual folder name, not the absolute path, so for most people, they will be something generic already such as the name of the character they are training, or the concept, or artist style. and if you have multiple folders, they are likely descriptive of what is in them, rather than anything meaningful anyways.

really, I don't understand at all why you care about it.
