### ISSUE TITLE
Cannot run either command line or popup

### ISSUE THREAD

**Issue by gLenahan** [derrian-distro/LoRA_Easy_Training_Scripts#11]
Running both popup and the command line scripts gives me the same error. Using the normal sd-scripts works just fine but running these gives me this error. I am using this in linux.

Traceback (most recent call last):
File "/home/garrett/Desktop/sd-scripts-0.4.2/lora_train_popup.py", line 862, in <module>
main()
File "/home/garrett/Desktop/sd-scripts-0.4.2/lora_train_popup.py", line 108, in main
setup_args(parser)
File "/home/garrett/Desktop/sd-scripts-0.4.2/lora_train_popup.py", line 343, in setup_args
util.add_dataset_arguments(parser, True, True, True)
TypeError: add_dataset_arguments() takes 3 positional arguments but 4 were given

**Comment by derrian-distro** [comment]
You need to update sd-scripts, you are using a version prior to the caption dropout system.

**Comment by derrian-distro** [comment]
You can do this by git cloning the project instead of download from the releases, as the releases are out of date. Alternatively you can reinstall sd-scripts using my installers, which will get you the newest version as well as give you the option to install the cudnn patch if you have a 30x0 or 40x0 card, or install the 10x0 patch if you have one of those
