### ISSUE TITLE
Not a true issue... more of a request...

### ISSUE THREAD

**Issue by DiggyDre** [derrian-distro/LoRA_Easy_Training_Scripts#137]
I got this thing up and working, and I am actually loving it over the Kohya Gui setup. I actually switched over to this one to check out the custom version of Cosine that is in here. There are only two things that I loved about the latest version of Kohya that I think would take this over the top.... I would love it if you could add a "stop training" button as well as a button that could easily pop open a tensor core window (if you have set up the proper folder for the graphs before you started training, of course). I think those two things would take this GUI over the top, but I am loving it as well as the simplicity. The fact that you don't have to copy a url and open it in the web browser is a plus as well because I love how it just opens up straight away, allowing you to get straight to work! Thank you for this awesomeness!

**Comment by derrian-distro** [comment]
first, Thanks for loving the UI! I put a lot of effort into making it as useful as I can! I can look into those features, but the "stop training" feature might be hard to implement due to the way my scripts are maintained, because I can't really directly modify sd-scripts, I can't tell it to stop training once it starts. for now, the only real way to kill the training early is to use ctrl + C on the command line, which will cause it to terminate immediately. if you are lucky (as in the GIL isn't stuck in the dying thread) you can just start another training and it will work fine.

I'll look into the tensor core thing though.

**Comment by DiggyDre** [comment]
> first, Thanks for loving the UI! I put a lot of effort into making it as useful as I can! I can look into those features, but the "stop training" feature might be hard to implement due to the way my scripts are maintained, because I can't really directly modify sd-scripts, I can't tell it to stop training once it starts. for now, the only real way to kill the training early is to use ctrl + C on the command line, which will cause it to terminate immediately. if you are lucky (as in the GIL isn't stuck in the dying thread) you can just start another training and it will work fine.
> 
> Just to double check, when you say tensor core, you mean the logging tensorboard? or something else?

Yes, the logging tensorboard is what I meant, lol. Sorry. And yes, I am still loving the GUI.

**Comment by derrian-distro** [comment]
alright, yeah, I should be able to get tensorboard to auto open without too much issue then, I'll look into adding it as an option to the start training button or something.
