### ISSUE TITLE
Linux Install Script

### ISSUE THREAD

**Issue by tokenwizard** [derrian-distro/LoRA_Easy_Training_Scripts#155]
Not an issue, just providing a simple bash script for installing on Linux. 
This assumes users already have the dependencies installed on their system, including python3.10 and python3-venv.

The script covers everything else from the git clone onward. 

```
#!/bin/bash

## Clone the git repo and change to that directory
git clone https://github.com/derrian-distro/LoRA_Easy_Training_Scripts
cd LoRA_Easy_Training_Scripts

## Init git submodules
git submodule init
git submodule update

## Change to sd-scripts directory, generate your python virtual environment and activate it
cd sd_scripts
python3.10 -m venv venv
source venv/bin/activate

## Install additional packages with pip
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt
pip install xformers
pip install -r ../requirements_ui.txt
pip install ../LyCORIS/.
pip install ../custom_scheduler/.
pip install bitsandbytes

## Configure accelerate
accelerate config

## Mark the run script executable
chmod u+x ../run.sh

## Run the damn thing
cd ../
./run.sh
```

Just paste the above code into a file called `setup.sh` and make is executable with `chmod u+x setup.sh`

**Comment by derrian-distro** [comment]
got it, I'll add it in the next update

**Comment by dege1000** [comment]
I wanted to add something, the latest version of xformers now requires pytorch 2.1.2+cu121, so I'm getting this error:
`WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for: PyTorch 2.1.2+cu121 with CUDA 1201 (you have 2.1.2+cu118)`
Then it would fail training with many errors about xformers not using CUDA

**Comment by derrian-distro** [comment]
alright, I'll update the installer. I don't personally use linux to train, nor do I have a linux distro to test on, so I am unaware of these issues usually

**Comment by dege1000** [comment]
> alright, I'll update the installer. I don't personally use linux to train, nor do I have a linux distro to test on, so I am unaware of these issues usually

I would recommend to instead use the same index url for xformers as torch, because a newer version of pytorch seems cause issues with bitstandbytes. That's at least what happens with my setup, this should work:
`#!/bin/bash

## Clone the git repo and change to that directory
git clone https://github.com/derrian-distro/LoRA_Easy_Training_Scripts
cd LoRA_Easy_Training_Scripts

## Init git submodules
git submodule init
git submodule update

## Change to sd-scripts directory, generate your python virtual environment and activate it
cd sd_scripts
python3.10 -m venv venv
source venv/bin/activate

## Install additional packages with pip
pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118
pip install -r requirements.txt
pip install xformers --index-url https://download.pytorch.org/whl/cu118
pip install -r ../requirements_ui.txt
pip install ../LyCORIS/.
pip install ../custom_scheduler/.
pip install bitsandbytes

## Configure accelerate
accelerate config

## Mark the run script executable
chmod u+x ../run.sh

## Run the damn thing
cd ../
./run.sh`

**Comment by derrian-distro** [comment]
hmm, alright

**Comment by derrian-distro** [comment]
oh right, I updated the install script on dev, I plan on pushing to main at some point soon after I let some people test the changes i've made
