### ISSUE TITLE
UI is broken (sometimes)

### ISSUE THREAD

**Issue by KrimsonWolf** [derrian-distro/LoRA_Easy_Training_Scripts#165]
I have loaded this on 2 computers and after a fresh install on both one works and one doesn't.  The one that works is an older windows 10 computer and the one that doesn't work is a newer windows 11 computer.  

Many of the UI buttons do not render at all on the newer computer.  I'm including a screenshot:

![image](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/assets/63033009/dea82d2a-6156-42ca-82b5-0dc2b73f0cc7)

it's weird because the checkbox appears to work when I click it but it's impossible to visually identify which checkboxes are checked.

This issue appears on every part of the screen not just the one pictured, including the subset args, I've also tried a few different themes and see the same problem in all the themes.

(though I do have a work around by saving the toml file and editing the properties directly there and then loading it again).

**Comment by marduk191** [comment]
I thought it was just me, must be a windows 11 thing because that's where mine lives too. I was about to spend a bunch of time trying to track it down finally, glad I checked. It is indeed broken, just keep track in your head and it works for now. It's been like this for months or more since it has been like that every since I installed it and my render rig is on 11.

**Comment by derrian-distro** [comment]
yeah, I've literally no clue why this happens. I unfortunately am unable to replicate this bug, perhaps I can add a mode that removes all the styling to fix this
