### ISSUE TITLE
Installation on windows need admin rights

### ISSUE THREAD

**Issue by B0rner** [derrian-distro/LoRA_Easy_Training_Scripts#225]
If you install `LoRA_Easy_Training_Scripts` on windows, following the readme-file (running `install.bat` in cmd), i came to the point, where a box pooepd up with the infomration, that the powershell needs to make some changes on the host and admin privileges are needed.

Why admin privileges are needed and what are the things, that the install script tries to do?

Is there a way to install the script(s) and run the gui/training in user-context only (on windows)?

Thank you.

**Comment by Jelosus2** [comment]
The admin priveleges are needed because kohya scripts (scripts used for training) have to install dependencies for the scripts to work and some of them usually get blocked by the Windows execution policy, so during the installation it has to disable the execution policy while it installs those dependencies. You can check the .bat files that are in charge of this task [here](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/blob/main/installables/change_execution_policy.bat) and [here](https://github.com/derrian-distro/LoRA_Easy_Training_Scripts/blob/main/installables/change_execution_policy_backup.bat) (backup in case 1st one fails). It's also [mentioned in the official repository](https://github.com/kohya-ss/sd-scripts?tab=readme-ov-file#windows-required-dependencies:~:text=Give%20unrestricted%20script%20access%20to%20powershell%20so%20venv%20can%20work%3A) in case you have any doubt.

**Comment by B0rner** [comment]
Thanks for clarification. 

I looked at the links. The “run as” calls can be seen there. But it's not clear to me yet which feature really needs these rights.

But this also means that you cannot install the scripts in a user-only context.

**Comment by Jelosus2** [comment]
The feature that needs the rights is the installation itself to install all the dependencies correctly.

**Comment by Jelosus2** [comment]
Any other thing you want to know, or can I close the issue?
