### ISSUE TITLE
Can't train lora based on SD 2.x models.

### ISSUE THREAD

**Issue by Seedmanc** [derrian-distro/LoRA_Easy_Training_Scripts#236]
Gives error "RuntimeError: Error(s) in loading state_dict for CLIPTextModel:
        Unexpected key(s) in state_dict: "text_model.embeddings.position_ids"".
Tried on SD2.1 768 ema pruned and hellcoder.
I checked the SD 2.x box. Anything else I need to configure?

**Comment by Seedmanc** [comment]
Tried that, didn't help.
I heard an advice on the same issue elsewhere to just delete this dict key, but I don't know how to do that.
I really want to play with SD2 model family, it's not as popular as 1 or XL, but XL barely works on my machine.

**Comment by Jelosus2** [comment]
How much VRAM you got? SD2 is not popular because is bad

**Comment by Seedmanc** [comment]
8Gb, but being bad is beside the point, I just want to experiment. 
I'm using EasyDiffusion and it only fits XL in memory with low_vram setting, which makes generation extremely slow. Training for XL even at 768x requires me to either load base model in 8bit or skip training TE (by the way, am I correct to assume that if I have no captions for dataset then training Text Encoder is pointless anyway?).

**Comment by Jelosus2** [comment]
yes, it's pointless. Also you can generate and train XL on 1024 res just fine on 8GB VRAM if you have 16GB or more of RAM

**Comment by Seedmanc** [comment]
So I took a closer look at the error and code, turns out it's not the SD2 checkpoint that has a redundant "position_ids" key, but the opposite, it's missing it, unlike SD1 models. The trained tries to load SD1-type CLIP and match its keys with SD2-type checkpoint, and fails. Why does it load an incompatible clip type?
Here it says that SD2+ models use ViT-H Clip instead of ViT-L: https://colab.research.google.com/github/pharmapsychotic/clip-interrogator/blob/main/clip_interrogator.ipynb
And indeed, the H type does not have this key, so it wouldn't have raised this error if it was used.

The loading happens in /backend/sd_scripts/library/train_util.py#4226 , but I don't know how to make it use the proper Clip.
However, setting manually strict=False made the trainer ignore the mismatched key and finish training. Whether it's proper usage or not, I do not know.

**Comment by Jelosus2** [comment]
> /backend/sd_scripts/library/train_util.py#4226

That's related to sd scripts and not the trainer

> So I took a closer look at the error and code, turns out it's not the SD2 checkpoint that has a redundant "position_ids" key, but the opposite, it's missing it, unlike SD1 models. The trainer tries to load SD1-type CLIP and match its keys with SD2-type checkpoint, and fails. Why does it load an incompatible clip type?
Here it says that SD2+ models use ViT-H Clip instead of ViT-L: https://colab.research.google.com/github/pharmapsychotic/clip-interrogator/blob/main/clip_interrogator.ipynb
And indeed, the H type does not have this key, so it wouldn't have raised this error if it was used.
The loading happens in /backend/sd_scripts/library/train_util.py#4226 , but I don't know how to make it use the proper Clip.
However, setting manually strict=False made the trainer ignore the mismatched key and finish training. Whether it's proper usage or not, I do not know.
Anyway, my EasyDiffusion doesn't seem to support SD2 loras anyway, so it's all meaningless.

So, should I close the issue or do you have any other question/problem?
