### ISSUE TITLE
Error when running install_sd_scripts_v5.bat

### ISSUE THREAD

**Issue by acncagua** [derrian-distro/LoRA_Easy_Training_Scripts#24]
situation
1. Place install_sd_scripts_v5.bat in the root of the J drive
2. Run the batch file
3. Error occurs.
![2023-02-24](https://user-images.githubusercontent.com/6410332/221123544-3d9b3e12-a97e-4b7b-b7da-042a83070793.png)

**Comment by derrian-distro** [comment]
Hi, I think it's related to the fact that you put it into the root of a drive, windows really doesn't like it when the root of a drive is used for most things.

**Comment by acncagua** [comment]
Created J:\sd folder and ran batch file in it
Result was no different
![2023-02-24 (1)](https://user-images.githubusercontent.com/6410332/221141099-7883f6d6-92a9-4de9-88f8-27256065f47b.png)
Sad to say.

**Comment by derrian-distro** [comment]
It seems like your windows doesn't like the cudnn patch. This might be related to the repo of it, as it's a bit finicky, I think the issue is that it's not able to download the script used to auto install the cudnn patch, which is just grabbed from kohya_ss as I haven't gotten around to creating my own version, it should work fine without it, but you won't be getting the speed boost from changing out the cudnn version.

If you want you can just manually download the cudnn parts and do it manually, I can write up a guide in a but as I am still not at my computer
