### ISSUE TITLE
UserWarning: torch.utils._pytree._register_pytree_node is deprecated

### ISSUE THREAD

**Issue by thezeroone98** [derrian-distro/LoRA_Easy_Training_Scripts#261]
i dont know how to fix this issue pls help, only 240 step but takes 1hours to finish
![22](https://github.com/user-attachments/assets/c9ce3146-9f9c-46fb-95ee-d335e0592184)

**Comment by Jelosus2** [comment]
Theres no error. Could you post a toml of your settings + your GPU name (be sure to specify if its a laptop GPU if its the case)?

**Comment by thezeroone98** [comment]
my toml here: https://files.catbox.moe/z00tgt.toml
Iam using pc with nvidia gtx 3060

**Comment by Jelosus2** [comment]
gtx 3060? Do you mean rtx 3060 (12GB VRAM version)? In any case, your toml looks pretty decent except for the resolution. For SDXL you want to use 1024x1024 but you're using 1024x2048 which is probably why it's taking more VRAM and it's likely to go to shared memory which is a ton slower. Also realisticly is 480 steps because you're using 2 batch size, the number displayed in the console is `real steps / batch size`

**Comment by thezeroone98** [comment]
ok thank you very much
