### ISSUE TITLE
"accelerate" not found

### ISSUE THREAD

**Issue by anphex** [derrian-distro/LoRA_Easy_Training_Scripts#28]
When I launch one of the both .bat files I always get this message. I installed with the latest installer v5 and installed cudnn but I can't see any "accelerate" file, folder or library. The installer should download and create this needed library during the setup or am I wrong?

**Comment by derrian-distro** [comment]
somehow accelerate wasn't installed, this is odd because accelerate is one of the requirements that get installed when the installer runs. you can probably fix this by activating the venv in a command line then pip installing it yourself. I do question why it didn't install in the first place though

**Comment by anphex** [comment]
My python path was set to 3.9.7. After I noticed and swapped it to 3.10.6 it worked!

**Comment by derrian-distro** [comment]
great! I'll go ahead and close the issue now. sorry that I couldn't help you more.
