### ISSUE TITLE
MacOS CUDA alternative

### ISSUE THREAD

**Issue by witfyl-ravped** [derrian-distro/LoRA_Easy_Training_Scripts#37]
Getting the libcudart.so error mentioned on your instructions page.

However I'm running on MacOS. Looking through the code I see a number of checks to see if CUDA is enable and revert to CPU if not. Am I missing that config step somewhere?

I also tried selecting MPS when running the `accelerate config` but ended up with the same error

**Comment by derrian-distro** [comment]
I don't know to be honest, I didn't exactly think about supporting Macs when developing the scripts. I really don't plan on directly supporting them as well, as it's pretty much impossible to run anything SD related in general. I doubt you'll find some way to get this to run without Cuda, because Kohya only supports Cuda in sd-scripts normally. 

that being said, My code only checks if you want to use CPU in the side scripts, as some people that don't have a good enough graphics card can use their CPU to do that. The main scripts are never intended to use anything but Cuda, as Kohya doesn't even have a built in way to change to CPU for training LoRA.

**Comment by witfyl-ravped** [comment]
Got it, interesting as I've gotten pretty far with Automatic and SD in general on my M2. I'm trying to pinpoint exactly where this is failing to see if I can pivot there as well.

**Comment by derrian-distro** [comment]
No there isn't, as Kohya doesn't have a place either
