### ISSUE TITLE
[Feature Request]  JSON-only mode for popups that launches without accelerate

### ISSUE THREAD

**Issue by s-ilent** [derrian-distro/LoRA_Easy_Training_Scripts#40]
The startup time of accelerate and other initialization can take a long time. Because the popup dialogues don't appear in the taskbar on Windows, sometimes it's like the script never finishes initializing at all. 

It would be nice if there was a version of run-popup that only sets up the JSON configuration.

**Comment by derrian-distro** [comment]
you can just run without accelerate by editing the batch files to say python rather than accelerate launch. this doesn't really change much though, as it still uses accelerate internally.

when it comes to passing in a json file and that being it, you can easily just activate the venv (venv\Scripts\activate), then call main.py by typing
python main.py 
you can use the optional argument --load_json_path to supply it a json file.

so in total, the command is as follows
python main.py --load_json_path "path_to_json.json"

I guess I could make a launcher that just swaps accelerate launch with python, and then let the popups go like normal, but I don't think this needs a full addition to the code
