### ISSUE TITLE
Cudnn Install Fails

### ISSUE THREAD

**Issue by lzardy** [derrian-distro/LoRA_Easy_Training_Scripts#44]
Hello, I cannot seem to install the cudnn patch for the initial installation as the cudnn.py file cannot be found.

**Comment by derrian-distro** [comment]
That is likely because the cudnn zip file actually failed. Sometimes the website that hosts the 8.6 patch gets flagged as malicious, that will prevent the cudnn path from being applied. If you want, you can manually download both the patch and the cudnn installer from bmaltas' repo [here](https://github.com/bmaltais/kohya_ss#optional-cudnn-86)

You can grab the associated python file from [here](https://raw.githubusercontent.com/bmaltais/kohya_ss/master/tools/cudann_1.8_install.py)

To run it you need to put it into a folder within sd_scripts, then activate the venv and run that python script.
