### ISSUE TITLE
Subset Name doesn't persist to TOML

### ISSUE THREAD

**Issue by DreamOfGit** [derrian-distro/LoRA_Easy_Training_Scripts#84]
When I create a new subset and name it, no key / value is generated in the TOML so when I reload that config, the subsets are all just blank / null..

Am I missing something / doing something dumb?

**Comment by derrian-distro** [comment]
The subset names are not processed when saved or loaded, that is correct. This is more or less for data safety, I might be able to add it but it it might require a lot of work. I'll get back to you on if I can add it or not

**Comment by DreamOfGit** [comment]
Is there a better way to persist subset names then other than an exported TOMA? Is that not what TOMA are for?

It's weird to build out 4 subsets named accurately than have them Null / Immutable after loading my TOMA later. Am I misunderstanding the purpose of them?

**Comment by derrian-distro** [comment]
the TOML files are how all args get exported so that they can be loaded up again. The subsets are not named internally, as they get a different more temporary moniker, as in they are tracked based on their "being" quite literally speaking their memory space. This is to allow the user to have the name be duplicate-able if necessary for some reason. The data safety isn't about privacy, it's more about the saving and loading process. The parser is already pretty complex, so I don't really want to add more complexity to it, as the TOML files are used in both the queue system, and to save and load user args, and I would have to ensure the change worked on both sections.

also, thanks for using the scripts, 100s of hours were put into them and I'm glad people are making use of them.

**Comment by DreamOfGit** [comment]
I don't think it's the end of the world losing Subset names. So if it's a huge workload / risk - probably better to invest your time elsewhere.

Either way thanks again, I've been experimenting with this to train LORA's the last few days and this was by far the easiest and simplest onboarding I've done to get up and running on a machine.

**Comment by derrian-distro** [comment]
I tried my hardest to make it as simple to install and setup as possible, so I'm glad you found it to be easy to install. I'll look into adding subset names to the toml files, but I can't really promise anything
